# Generated by Django 6.0 on 2026-01-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lat', models.CharField(default='', max_length=255)),
                ('title_kiril', models.CharField(default='', max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_lat', models.TextField(default='')),
                ('description_kiril', models.TextField(default='')),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.category')),
            ],
        ),
    ]
